// <auto-generated />
namespace WebApiTest2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _15oper : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_15oper));
        
        string IMigrationMetadata.Id
        {
            get { return "202103061125315_15oper"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
