// <auto-generated />
namespace WebApiTest2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _10oper : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_10oper));
        
        string IMigrationMetadata.Id
        {
            get { return "202102281139081_10oper"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
